name: 'Torchify'
version: '@mod_version@'
api-version: '@minecraft_version@'
main: 'lol.hub.torchify.Plugin'
description: 'Light it up!'
website: 'https://github.com/nothub/Torchify'
authors: [ 'nothub' ]
contributors: [ ]

commands:
  torchify:
    description: 'Toggle auto-torching'
    usage: '/torchify'
    aliases: [ 'autotorch' ]
    permission: torchify.toggle

permissions:
  torchify.toggle:
    default: true
